feat: ✨ add `displayName` config option
EvanBacon/expo-apple-targets pull request #53
Opened 2024-11-14 20:45 UTC by goztrk

This PR adds a new config option called `displayName` to specify a different display name if desired. Does not break any existing functionalities.

2025-01-20 16:25 UTC, ender-null commented
is this going to be merged any time soon?

2025-01-24 08:11 UTC, resdevd commented
@EvanBacon It would be great if you can review this PR. Currently the watch display name seems to be just "watch".

2025-01-24 20:26 UTC, EvanBacon commented on packages/apple-targets/src/withXcodeChanges.ts
> +      INFOPLIST_KEY_CFBundleDisplayName: displayName,
Heads up, you should be able to just set this key in your targets/<target>/Info.plist (CFBundleDisplayName) to override the default here. Would be nice if we could just have one `name` property in the config.

2025-01-24 20:38 UTC, EvanBacon requested changes
The logic here should be flipped. The `name` should be the display name and the safer sanitized name should be inferred from the `name` automatically. I'll take a stab at this.

2025-01-27 00:41 UTC, EvanBacon commented
Closing in favor of #88

2025-01-27 00:41 UTC, closed without merging

2025-02-13 09:07 UTC, julian-gargicevich commented
@goztrk did you manage to get it to work? Adding CFBundleDisplayName to my info.plist does nothing, and I want my watch name to be the same as the main app, and the provisioning profiles stop working if I use the same name in the expo-target.config file